# Generated by Django 2.2.5 on 2020-04-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200409_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amnities',
            new_name='amenities',
        ),
    ]
